name: React CI

on:
  push:
    branches:
      - main
  
  pull-request:
    branches:
      - main

jobs:

  hello:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "Hello world"
      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: install package
        run:  npm install
      
      - name: build project
        run: npm run build
